# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'data_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_service.proto\"\x1c\n\x0b\x44\x61taRequest\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\x0c\x44\x61taResponse\x12\x11\n\tdataframe\x18\x01 \x01(\x0c\x32\x35\n\x0b\x44\x61taService\x12&\n\x07GetData\x12\x0c.DataRequest\x1a\r.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=22
  _globals['_DATAREQUEST']._serialized_end=50
  _globals['_DATARESPONSE']._serialized_start=52
  _globals['_DATARESPONSE']._serialized_end=85
  _globals['_DATASERVICE']._serialized_start=87
  _globals['_DATASERVICE']._serialized_end=140
# @@protoc_insertion_point(module_scope)
